import type { IResourceItem } from "@refinedev/core";

import {
  DashboardOutlined,
  TeamOutlined,
  UserOutlined,
  UserSwitchOutlined,
  AppstoreOutlined,
  BankOutlined,
  SettingOutlined,
  ProfileOutlined,
  SafetyCertificateOutlined,
  ShoppingCartOutlined,
  TagsOutlined,
  ToolOutlined,
  AuditOutlined,
} from "@ant-design/icons";

export const resources: IResourceItem[] = [
  {
    name: "dashboard",
    list: "/",
    meta: {
      label: "Bảng điều khiển",
      icon: <DashboardOutlined />,
    },
  },
  {
    name: "products",
    list: "/products",
    create: "/products/create",
    clone: "/products/:id/clone",
    edit: "/products/:id/edit",
    show: "/products/:id",
    meta: {
      canDelete: true,
      label: "Sản phẩm",
      icon: <AppstoreOutlined />,
    },
  },
  {
    name: "users",
    list: "/users",
    create: "/users/create",
    clone: "/users/:id/clone",
    edit: "/users/:id/edit",
    show: "/users/:id",
    meta: {
      canDelete: true,
      label: "Người dùng",
      icon: <UserOutlined />,
    },
  },
  {
    name: "roles",
    list: "/roles",
    create: "/roles/create",
    clone: "/roles/:id/clone",
    edit: "/roles/:id/edit",
    show: "/roles/:id",
    meta: {
      canDelete: true,
      label: "Vai trò hệ thống",
      icon: <UserSwitchOutlined />,
    },
  },
  {
    name: "roleclaims",
    identifier: "data-roleclaims",
    list: "/roleclaims",
    create: "/roleclaims/create",
    clone: "/roleclaims/:id/clone",
    edit: "/roleclaims/:id/edit",
    show: "/roleclaims/:id",
    meta: {
      canDelete: true,
      label: "Quyền vai trò",
      icon: <TeamOutlined />,
    },
  },
  {
    name: "categories",
    list: "/categories",
    create: "/categories/create",
    edit: "/categories/:id/edit",
    show: "/categories/:id",
    meta: {
      canDelete: true,
      label: "Danh mục chung",
      icon: <TagsOutlined />,
    },
  },
  {
    name: "departments",
    list: "/departments",
    create: "/departments/create",
    edit: "/departments/:id/edit",
    show: "/departments/:id",
    meta: {
      canDelete: true,
      label: "Phòng ban / Đơn vị",
      icon: <BankOutlined />,
    },
  },
  {
    name: "proposal-configs",
    list: "/proposal-configs",
    create: "/proposal-configs/create",
    edit: "/proposal-configs/:id/edit",
    show: "/proposal-configs/:id",
    meta: {
      canDelete: true,
      label: "Cấu hình đề xuất",
      icon: <SettingOutlined />,
    },
  },
  {
    name: "config-categories",
    list: "/config-categories",
    create: "/config-categories/create",
    edit: "/config-categories/:id/edit",
    show: "/config-categories/:id",
    meta: {
      canDelete: true,
      label: "DM Cấu hình",
      icon: <ProfileOutlined />,
    },
  },
  {
    name: "config-approvers",
    list: "/config-approvers",
    create: "/config-approvers/create",
    edit: "/config-approvers/:id/edit",
    show: "/config-approvers/:id",
    meta: {
      canDelete: true,
      label: "Người duyệt",
      icon: <SafetyCertificateOutlined />,
    },
  },
  {
    name: "purchase-requests",
    list: "/purchase-requests",
    create: "/purchase-requests/create",
    edit: "/purchase-requests/:id/edit",
    show: "/purchase-requests/:id",
    meta: {
      canDelete: true,
      label: "Đề xuất mua sắm",
      icon: <ShoppingCartOutlined />,
    },
  },
  {
    name: "purchase-request-categories",
    list: "/purchase-request-categories",
    create: "/purchase-request-categories/create",
    edit: "/purchase-request-categories/:id/edit",
    show: "/purchase-request-categories/:id",
    meta: {
      canDelete: true,
      label: "DM Đề xuất",
      icon: <TagsOutlined />,
    },
  },
  {
    name: "purchase-request-items",
    list: "/purchase-request-items",
    create: "/purchase-request-items/create",
    edit: "/purchase-request-items/:id/edit",
    show: "/purchase-request-items/:id",
    meta: {
      canDelete: true,
      label: "Vật tư đề xuất",
      icon: <ToolOutlined />,
    },
  },
  {
    name: "purchase-request-logs",
    list: "/purchase-request-logs",
    create: "/purchase-request-logs/create",
    edit: "/purchase-request-logs/:id/edit",
    show: "/purchase-request-logs/:id",
    meta: {
      canDelete: true,
      label: "Lịch sử đề xuất",
      icon: <AuditOutlined />,
    },
  },
];